apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-flag-service
  namespace: toggle-master
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
